
WITH t AS ( 
  SELECT w.NAME, count(*) AS PROJECT_COUNT
  FROM WORKER w 
  INNER JOIN PROJECT_WORKER pw 
  ON w.ID = WORKER_ID
  GROUP BY w.ID
)
SELECT t.NAME, t.PROJECT_COUNT 
FROM t
WHERE t.PROJECT_COUNT = (SELECT max(PROJECT_COUNT) FROM t);